on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n rundeck -g rundeckae78-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n rundeck --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n rundeck --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n rundeck --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: rundeck.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t rundeck.azurecr.io/rundeck:${{ github.sha }}
        docker push rundeck.azurecr.io/rundeck:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_rundeck_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rundeckabfb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rundeckabfb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rundeckabfb
        container-registry-url: rundeck.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: rundeckdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: rundeckabfb
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          rundeck.azurecr.io/rundeck:${{ github.sha }}
        imagepullsecrets: |
          rundeckdockerauth